server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/friends?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  swagger:
    show: true

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml